#!/bin/bash

# bashism: {}

set -e

FGDB_BASE=/var/www/fgdb.rb
FGDB_MASTER=/home/dbadmin/fgdb.rb

die() {
      echo "Error: $@"
      exit 1
}

if [ "$(id -u)" != "0" ]; then
   die "This script requires root"
fi

if [ ! -d $FGDB_BASE ]; then
   die "Could not find installation at $FGDB_BASE"
fi

chown -R dbadmin:dbadmin $FGDB_BASE
chown -R dbadmin:dbadmin $FGDB_BASE/{log,public,tmp,config/environment.rb,config/rt_metadata.txt}
# git group has dbadmin, and any committer
chown -R ryan52:git $FGDB_BASE/.git

chown -R dbadmin:dbadmin $FGDB_MASTER
chown -R root:dbadmin $FGDB_BASE/doc/examples/database_logrotate{,_daily}.conf
chown -R ryan52:git $FGDB_MASTER/.git

chown dbadmin:dbadmin /var/www/fgdb.rb/config/rt_metadata.txt
chmod 644 /var/www/fgdb.rb/config/rt_metadata.txt
