#!/bin/sh

STDOUT_FILE=$(mktemp)
STDERR_FILE=$(mktemp)

"$@" >$STDOUT_FILE 2>$STDERR_FILE
RETURN_VALUE=$?

cat $STDOUT_FILE
cat $STDERR_FILE  | grep -Ev ' is deprecated,? ' | grep -v ' called from ' | grep -v ' will be deprecated ' | grep -v 'against to UTF-8 string' >&2

rm $STDOUT_FILE $STDERR_FILE

exit $RETURN_FILE
