#!/bin/sh

INCOME=/srv/backup-extras/
LIST=$(ls $INCOME | grep .sql$)

set -e

if [ ! -z "$LIST" ]; then
   cd $INCOME
   for FILE in $LIST; do
      cat $FILE | bzip2 -c - > ${FILE}.bz2
      rm -fr $FILE
   done
fi

